export const ErrorCode = {
  UNKNOWN: 'UNKNOWN',
  INVALID_ENVELOPE: 'INVALID_ENVELOPE',
  UNKNOWN_EVENT_TYPE: 'UNKNOWN_EVENT_TYPE',
  INVALID_STREAM_ID: 'INVALID_STREAM_ID',
  HANDSHAKE_REQUIRED: 'HANDSHAKE_REQUIRED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  IDEMPOTENCY_MISMATCH: 'IDEMPOTENCY_MISMATCH',
  INTENT_NOT_FOUND: 'INTENT_NOT_FOUND',
  RUN_NOT_FOUND: 'RUN_NOT_FOUND',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  POLICY_REJECTED: 'POLICY_REJECTED',
  APPROVAL_REQUIRED: 'APPROVAL_REQUIRED',
} as const;
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
